/**
 * 翻译字典模块
 * 
 * safeGlobalDict:  安全长句字典，不会与代码变量冲突，可直接全局替换
 * riskyShortWords: 危险短词字典，只能在 UI 属性上下文中替换，否则会导致白屏
 */

const safeGlobalDict = {
    "Manage Account": "管理账号",
    "Manage your account and billing": "管理您的账号与账单",
    "Invite Team Members": "邀请团队成员",
    "Accelerate development, shared knowledge, and context across your team": "跨团队加速开发并共享知识与上下文",
    "Preferences": "偏好设置",
    "Sync layouts across windows": "跨窗口同步布局",
    "When enabled, all windows share the same layout": "启用后，所有窗口共享相同的布局",
    "Editor Settings": "编辑器设置",
    "Configure font, formatting, minimap and more": "配置字体、格式化、缩略图等",
    "Keyboard Shortcuts": "键盘快捷键",
    "Configure keyboard shortcuts": "配置键盘快捷键",
    "Import Settings from VS Code": "从 VS Code 导入设置",
    "Import settings, extensions, and keybindings from VS Code": "导入 VS Code 的设置、扩展和快捷键绑定",
    "See warnings and tips that you've hidden": "查看您已隐藏的警告和提示",
    "Layout": "布局",
    "Conversation Density": "对话密度",
    "Choose how much detail Agent tool calls show in the conversation": "选择智能体工具调用在对话中显示的详细程度",
    "Title Bar": "标题栏",
    "Show title bar in agent layout": "在智能体布局中显示标题栏",
    "Status Bar": "状态栏",
    "Show status bar": "显示状态栏",
    "Show status bar at the bottom of the window": "在窗口底部显示状态栏",
    "Review Control Location": "审查控件位置",
    "Show inline diff review controls in top level breadcrumbs or floating island": "在顶层面包屑或悬浮岛中显示内联差异审查控件",
    "Auto-hide editor when empty": "空闲时自动隐藏编辑器",
    "When all editors are closed, hide the editor area and maximize chat": "关闭所有编辑器时，隐藏编辑器并最大化聊天窗口",
    "Open chat as editor tabs": "以编辑器标签页打开聊天",
    "Show chats as editor tabs inside the chat area instead of the legacy stacked view": "在聊天区域内以编辑器标签页显示聊天，而不是旧版堆叠视图",
    "Notifications": "通知",
    "System Notifications": "系统通知",
    "Show system notifications when Agent completes or needs attention": "智能体完成任务或需要注意时显示系统通知",
    "System Tray Icon": "系统托盘图标",
    "Show Cursor in system tray": "在系统托盘显示 Cursor",
    "Menu Bar Icon": "菜单栏图标",
    "Show Cursor in menu bar": "在菜单栏中显示 Cursor",
    "Completion Sound": "完成提示音",
    "Play a sound when Agent finishes responding": "智能体完成响应时播放提示音",
    "Privacy": "隐私",
    "Rules, Skills, Subagents": "规则、技能与子智能体",
    "Tools & MCP": "工具与 MCP",
    "Indexing & Docs": "索引与文档",
    "Cloud Agents": "云端智能体",
    "Team Plan": "团队版",
    "Plugins": "插件",
    "Search settings": "搜索设置",
    "Auto-Run Mode": "自动运行模式",
    "Choose how Agent runs tools like command execution, MCP, and file writes.": "选择智能体如何运行命令执行、MCP 和文件写入等工具。",
    "Command Allowlist": "命令白名单",
    "Commands that can run automatically": "可自动运行的命令",
    "MCP Allowlist": "MCP 白名单",
    "MCP tools that can run automatically. Format: 'server:tool', 'server:*' for all tools from a server, '*:tool' for a tool from any server, or *:* for all tools from all servers": "可自动运行的 MCP 工具。格式：'server:tool'、'server:*' 表示某服务器的全部工具、'*:tool' 表示任意服务器的某工具、*:* 表示所有服务器的所有工具",
    "Fetch Domain Allowlist": "请求域名白名单",
    "Domains that Agent can fetch from automatically. Use '*' for all domains, '*.example.com' for wildcard subdomains.": "智能体可自动请求的域名。使用 '*' 匹配所有域名，'*.example.com' 匹配通配符子域名。",
    "Auto-Approved Mode Transitions": "自动批准的模式切换",
    "Mode transitions that will be automatically approved without prompting.": "无需提示即自动批准的模式切换。",
    "Browser Protection": "浏览器保护",
    "Prevent Agent from automatically running Browser tools": "阻止智能体自动运行浏览器工具",
    "MCP Tools Protection": "MCP 工具保护",
    "Prevent Agent from automatically running MCP tools": "阻止智能体自动运行 MCP 工具",
    "File-Deletion Protection": "文件删除保护",
    "Prevent Agent from deleting files automatically": "阻止智能体自动删除文件",
    "External-File Protection": "外部文件保护",
    "Prevent Agent from creating or modifying files outside of the workspace automatically": "阻止智能体自动创建或修改工作区外的文件",
    "Default Location": "默认位置",
    "Where to open new agents": "新智能体的打开位置",
    "Text Size": "文字大小",
    "Adjust the conversation text size": "调整对话文字大小",
    "Ask Every Time": "每次询问",
    "Use Allowlist": "使用白名单",
    "Run Everything": "运行所有",
    "Settings": "设置",
    "Extra Large": "超大",
    "Cursor Tab": "Cursor Tab 补全",
    "Context-aware, multi-line suggestions around your cursor based on recent edits": "基于最近编辑，在光标周围提供上下文感知的多行建议",
    "Partial Accepts": "部分接受",
    "Accept the next word of a suggestion via Ctrl+RightArrow": "通过 Ctrl+右箭头接受建议的下一个单词",
    "Suggestions While Commenting": "注释时建议",
    "Allow Tab to trigger while in a comment region": "允许在注释区域中触发 Tab 补全",
    "Whitespace-Only Suggestions": "仅空白建议",
    "Suggest edits like new lines and indentation that modify whitespace only": "仅建议修改空白的编辑，如换行和缩进",
    "Automatically import necessary modules for TypeScript": "自动导入 TypeScript 所需的模块",
    "Auto Import for Python": "Python 自动导入",
    "Enable auto import for Python. This is a beta feature.": "启用 Python 自动导入。这是一个测试功能。",
    "Provide domain-specific knowledge and workflows for the agent": "为智能体提供特定领域的知识和工作流",
    "Include third-party Plugins, Skills, and other configs": "包含第三方插件、技能和其他配置",
    "Automatically import agent configs from other tools": "自动从其他工具导入智能体配置",
    "Use Rules to guide agent behavior, like enforcing best practices or coding standards. Rules can be applied always, by file path, or manually.": "使用规则引导智能体行为，例如强制执行最佳实践或编码标准。规则可以始终应用、按文件路径应用或手动应用。",
    "Skills are specialized capabilities that help the agent accomplish specific tasks. Skills will be invoked by the agent when relevant or can be triggered manually with / in chat.": "技能是帮助智能体完成特定任务的专业能力。智能体会在相关时自动调用技能，也可在聊天中通过 / 手动触发。",
    "No Skills Yet": "暂无技能",
    "Skills help the agent accomplish specific tasks": "技能帮助智能体完成特定任务",
    "New Skill": "新建技能",
    "Create specialized agents for complex tasks. Subagents can be invoked by the agent to handle focused work in parallel.": "创建用于复杂任务的专业智能体。子智能体可被主智能体调用，以并行处理专项工作。",
    "No Subagents Yet": "暂无子智能体",
    "Create specialized agents to handle focused tasks": "创建专业智能体来处理专项任务",
    "New Subagent": "新建子智能体",
    "Create reusable workflows triggered with / prefix in chat. Use commands to standardize processes and make common tasks more efficient.": "创建在聊天中通过 / 前缀触发的可复用工作流。使用命令标准化流程，提高常见任务的效率。",
    "No Commands Yet": "暂无命令",
    "Create commands to build reusable workflows": "创建命令以构建可复用工作流",
    "New Command": "新建命令",
    "+ New": "+ 新建",

    // ── 智能体设置 ──
    "Auto-Clear Chat": "自动清除聊天",
    "After periods of inactivity, open the Agent Pane to a new conversation": "一段时间不活动后，将智能体面板打开为新对话",
    "Submit with Ctrl + Enter": "使用 Ctrl + Enter 提交",
    "When enabled, Ctrl + Enter submits chat and Enter inserts a newline": "启用后，Ctrl + Enter 提交聊天，Enter 插入换行",
    "Max Tab Count": "最大标签页数",
    "Limit how many chat tabs can be open at once": "限制同时打开的聊天标签页数量",
    "Queue Messages": "消息队列",
    "Adjust the default behavior of sending a message while Agent is running": "调整智能体运行时发送消息的默认行为",
    "Send after current message": "当前消息后发送",
    "Stop & send right away": "立即停止并发送",
    "Usage Summary": "用量摘要",
    "When to show the usage summary at the bottom of the chat pane": "何时在聊天面板底部显示用量摘要",
    "Agent Autocomplete": "智能体自动补全",
    "Contextual suggestions while prompting Agent": "向智能体提问时提供上下文建议",

    // ── Agent Review ──
    "Start Agent Review on Commit": "代码提交时启动智能体审查",
    "Automatically review your changes for issues after each commit": "在每次提交后自动审查您的更改是否存在问题",
    "Include Submodules in Agent Review": "在智能体审查中包含子模块",
    "Include changes from Git submodules in the review": "在审查中包含 Git 子模块的更改",
    "Include Untracked Files in Agent Review": "在审查中包含未跟踪文件",
    "Include untracked files (new files not yet added to Git) in the review": "在审查中包含未跟踪文件（尚未添加到 Git 的新文件）",
    "Default Approach": "默认方式",
    "Choose between quick or more thorough, higher-cost analysis": "选择快速或更彻底、成本更高的分析",

    // ── Context & Applied Changes ──
    "Web Search Tool": "网络搜索工具",
    "Allow Agent to search the web for relevant information": "允许智能体在网络上搜索相关信息",
    "Auto-Accept Web Search": "自动接受网络搜索",
    "Skip approval dialog; Agent may run web searches automatically": "跳过批准对话；智能体可自动运行网络搜索",
    "Web Fetch Tool": "网页获取工具",
    "Allow Agent to fetch content from URLs": "允许智能体从 URL 获取内容",
    "Hierarchical Cursor Ignore": "分层 Cursor 忽略",
    "Apply .cursorignore files to all subdirectories. Changing this setting will require a restart of Cursor.": "将 .cursorignore 文件应用到所有子目录。更改此设置需要重启 Cursor。",
    "Ignore Symlinks in Cursor Ignore Search": "在 Cursor 忽略搜索中忽略符号链接",
    "Use with caution. Skip symlinks during .cursorignore file discovery. Only enable if your repository has many symlinks and all .cursorignore files are reachable without them. Changing this setting will require a restart of Cursor.": "谨慎使用。在发现 .cursorignore 文件时跳过符号链接。仅当您的仓库存有许多符号链接，且没有符号链接也能访问所有 .cursorignore 文件时才启用。更改此设置需要重启 Cursor。",
    "Applying Changes": "应用更改",
    "Inline Diffs": "内联差异",
    "Show inline diff decorations in the editor instead of only showing changes in the review panel": "在编辑器中显示内联差异装饰，而不是仅在审查面板中显示更改",
    "Jump to Next Diff on Accept": "接受时跳转到下一个差异",
    "Automatically jump to the next diff when accepting changes with Ctrl+Y": "使用 Ctrl+Y 接受更改时自动跳转到下一个差异",
    "Auto Format on Agent Finish": "智能体完成时自动格式化",
    "Automatically format files when the agent finishes": "智能体完成任务时自动格式化文件",

    // ── Inline Editing & Terminal ──
    "Inline Editing & Terminal": "内联编辑与终端",
    "Legacy Terminal Tool": "旧版终端工具",
    "Use the legacy terminal tool in agent mode, for use on systems with unsupported shell configurations": "在智能体模式下使用旧版终端工具，适用于 shell 配置不受支持的系统",
    "Toolbar on Selection": "选中时显示工具栏",
    "Show Add to Chat & Quick Edit buttons when selecting code": "选择代码时显示“添加到聊天”和“快速编辑”按钮",
    "Auto-Parse Links": "自动解析链接",
    "Automatically parse links when pasted into Quick Edit (Ctrl+K) input": "粘贴到快速编辑 (Ctrl+K) 输入框时自动解析链接",
    "Themed Diff Backgrounds": "主题差异背景",
    "Use themed background colors for inline code diffs": "为内联代码差异使用主题背景色",
    "Terminal Hint": "终端提示",
    "Show a hint for Ctrl+K in the Terminal": "在终端中显示 Ctrl+K 提示",
    "Preview Box for Terminal Ctrl+K": "终端 Ctrl+K 的预览框",
    "Use a preview box instead of streaming responses directly into the shell": "使用预览框而不是将响应直接流式传输到 shell 中",
    "Collapse Auto-Run Commands": "折叠自动运行命令",
    "Collapse auto-run command output by default in Terminal command previews": "在终端命令预览中默认折叠自动运行的命令输出",

    // ── Voice Mode & Attribution ──
    "Voice Mode": "语音模式",
    "Submit Keywords": "提交关键字",
    "Custom keywords that trigger auto-submit in voice mode. Only single words (no spaces) are allowed. Punctuation and capitalization are ignored.": "在语音模式下触发自动提交的自定义关键字。仅允许单个单词（无空格）。忽略标点符号和大小写。",
    "Attribution": "代码署名",
    "Commit Attribution": "提交署名",
    "Mark Agent commits as 'Made with Cursor'": "将智能体提交标记为 'Made with Cursor'",
    "PR Attribution": "PR 署名",
    "Mark pull requests as made with Cursor": "将拉取请求标记为使用 Cursor 制作",

    // ── Privacy ──
    "Privacy Mode": "隐私模式",
    "Your code data will not be trained on or used to improve the product. Code may be stored to provide features such as Background Agent.": "您的代码数据不会被用于训练或改进产品。代码可能会被存储以提供后台智能体等功能。",
    "Data Sharing is controlled by the team admin. Configure here.": "数据共享由团队管理员控制。在此配置。",
    "Data Sharing Enabled": "数据共享已启用",
    "Your codebase, prompts, edits and other usage data will be stored and trained on by Cursor to improve the product.": "您的代码库、提示词、编辑和其他使用数据将被 Cursor 存储并用于训练，以改进产品。",
    "Data Sharing is controlled by your team admin.": "数据共享由您的团队管理员控制。",
    "Learn more about Data Sharing.": "了解更多关于数据共享的信息。",

    // ── Miscellaneous ──
    "Accept the next word of a suggestion via Ctrl+RightArrow": "通过 Ctrl+RightArrow 接受建议的下一个词",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要的模块",

    // ── Usage Limits ──
    "Increase limits for faster responses": "提高限制以获得更快的响应",
    "You're over your current usage limit and your requests are being processed with Auto in the slow queue.": "您已超出当前配置的使用量限制，您的请求正以临时排队方式在慢速队列中处理。",
    "Set new limit": "设置新限制",

    // ── Cloud / Background Agents ──
    "Get Started": "开始使用",
    "Cloud Agents require a Git repository in an open folder.": "云智能体需要打开的文件夹中包含 Git 仓库。",
    "Open a Git repository": "打开 Git 仓库",
    "Background agents only work in folders with a git repository.": "后台智能体仅在包含 git 仓库的文件夹中工作。",
    "Please open a folder that contains a git repository to use this feature.": "请打开包含 git 仓库的文件夹以使用此功能。",

    // ── Extensions / Marketplace ──
    "Extend Cursor with Skills, Rules, Agents, Hooks, and MCPs": "使用技能、规则、智能体、钩子和 MCP 扩展 Cursor",

    // ── Network ──
    "HTTP Compatibility Mode": "HTTP 兼容模式",
    "HTTP/2 is recommended for low-latency streaming. In some corporate proxy and VPN environments, the compatibility mode may need to be lowered.": "推荐使用 HTTP/2 以实现低延迟流式传输。在某些企业代理和 VPN 环境中，可能需要降低兼容模式。",
    "Required Domains": "必需的域名",
    "These domains must be accessible for Cursor to function. Add them to your firewall or proxy allowlist.": "必须可访问这些域名，Cursor 才能正常工作。请将它们添加到您的防火墙或代理白名单中。",
    "Network Diagnostics": "网络诊断",
    "Check network connectivity to all Cursor services": "检查与所有 Cursor 服务的网络连接",

    // ── Update ──
    "Update Access": "更新通道",
    "By default, get notifications for stable updates. In Early Access, pre-release builds may be unstable for production work.": "默认情况下，接收稳定版更新的通知。在抢先体验通道中，预发布版本可能不稳定，不建议用于生产环境。",
    "Extension RPC Tracer": "扩展 RPC 追踪器",
    "Log extension host RPC messages to JSON files viewable in Perfetto for performance analysis. Requires a restart to take effect.": "将扩展主机的 RPC 消息记录到 JSON 文件中，可在 Perfetto 中查看以进行性能分析。需要重启才能生效。",

    // ── Hooks ──
    "Hooks let you run custom scripts at specific points during the agent's execution to modify behavior, enforce policies, or add custom logging.": "钩子允许您在智能体执行的特定点运行自定义脚本，以修改行为、强制执行策略或添加自定义日志。",
    "No hooks configured": "未配置钩子",
    "No hook executions yet": "暂无钩子执行记录",

    // ── Tools / Browser ──
    "Browser Automation": "浏览器自动化",
    "Browser automation disabled": "浏览器自动化已禁用",
    "Show Localhost Links in Browser": "在浏览器中显示 Localhost 链接",
    "Automatically open localhost links in the Browser Tab": "自动在浏览器标签页中打开 localhost 链接",

    // ── Features / Documentation Links ──
    "Learn about Rules": "了解规则",
    "Learn about Skills": "了解技能",
    "Learn about Subagents": "了解子智能体",
    "Learn about Commands": "了解命令",
    "User Rule": "用户规则",
    "Project Rule": "项目规则",
    "Add from GitHub/GitLab": "从 GitHub/GitLab 添加",

    // ── Commands & MCP ──
    "Project Command": "项目命令",
    "User Command": "用户命令",
    "New MCP Server": "新建 MCP 服务器",
    "Add a Custom MCP Server": "添加自定义 MCP 服务器",

    // ── Models ──
    "Balanced quality and speed, recommended for most tasks": "平衡质量和速度，推荐用于大多数任务",
    "Multiple models require a Git repository.": "使用多模型功能需要 Git 仓库。",

    // ── Dialogs ──
    "Are you sure? This replaces your settings and extensions with your vscode ones. This cannot be undone.": "确定要继续吗？这将用您的 VS Code 设置和扩展替换当前的设置和扩展。此操作无法撤销。",
    "Reset \"Don't Ask Again\" Dialogs": "重置“不再询问”弹窗",
    "Reset \"Don’t Ask Again\" Dialogs": "重置“不再询问”弹窗",
    "See warnings and tips that you've hidden": "查看您已隐藏的警告和提示",
    "See warnings and tips that you’ve hidden": "查看您已隐藏的警告和提示",
    "No Hidden Dialogs Yet": "暂无隐藏的弹窗",
    "You haven't marked any dialogs as \"Don't ask again\". Any hidden dialogs will appear here to manage.": "您尚未将任何弹窗标记为“不再询问”。任何隐藏的弹窗都将显示在此处以供管理。",
    "You haven’t marked any dialogs as \"Don’t ask again\". Any hidden dialogs will appear here to manage.": "您尚未将任何弹窗标记为“不再询问”。任何隐藏的弹窗都将显示在此处以供管理。",

    // ── 下面原本误放入了短词字典 ──
    "Submit with ": "使用 ",
    "When enabled, ": "启用后，",
    " submits chat and ": " 提交聊天，",
    " inserts a newline": " 插入换行",
    "Accept the next word of a suggestion via ": "使用 ",
    " accept the next word of a suggestion": " 接受建议的下一个词",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要的模块",

    // Codebase 相关设置
    "Codebase": "代码库",
    "Codebase Indexing": "代码库索引",
    "Delete Index": "删除索引",
    "Index New Folders": "索引新文件夹",
    "Automatically index any new folders with fewer than 250,000 files": "自动索引少于 250,000 个文件的新文件夹",
    "View included files.": "查看已包含的文件。",
    "Team-Level Repository Control": "团队级代码库控制",
    "Disable AI features in specific repositories based on file pattern": "基于文件匹配模式在特定代码库中禁用 AI 功能",
    "Index Repositories for Instant Grep": "为 Instant Grep 索引代码库",
    "Automatically index repositories to speed up Grep searches. All data is stored locally.": "自动索引代码库以加速 Grep 搜索。所有数据均存储在本地。",
    "Crawl and index custom resources and developer docs": "爬取并索引自定义资源和开发者文档",
    "No Docs Added": "未添加文档",
    "Add Doc": "添加文档",
    "Increase limits for faster responses": "提升额度以获取更快响应",
    "Automatically jump to the next diff when accepting changes with ": "当接受更改时，自动跳转到下一个差异，借助 ",
    "Ignore Files in ": "忽略包含在 ",
    "Ignore Files in .cursorignore": "忽略 .cursorignore 中的文件",
    "Nightly Updates Apply Automatically": "每夜更新自动应用",
    "Copy Domains": "复制域名",
    "Run Diagnostic": "运行诊断",
    "Learn about codebase indexing": "了解代码库索引",
    "Embed codebase for improved contextual understanding and knowledge. Embeddings and metadata are stored in the": "嵌入代码库以增强上下文理解和知识。嵌入向量和元数据存储在",
    ", but all code is stored locally.": "，但所有代码都存储在本地。",
    "Agent Review": "智能体审查",
    "Data Sharing is controlled by ": "数据共享由",
    "team admin.": "团队管理员控制。",
    "Nightly builds will silently download and install updates without prompting you.": "每夜版本将静默下载并安装更新，不会提示您。",
    "Keybinding: editor.action.inlineSuggest.acceptNextWord": "快捷键: editor.action.inlineSuggest.acceptNextWord",
    "Keybinding: ": "快捷键: ",
    "Keybinding:": "快捷键:",

    // ── Agents Window 横幅 ──
    "Meet the new Agents Window": "认识全新的智能体窗口",
    "Run many agents in parallel \\u2014 across repos, locally, on remote SSH, and in the cloud.": "并行运行多个智能体——跨仓库、本地、远程 SSH 以及云端。",
    "Jump back to the Agents Window to keep working across repos.": "返回智能体窗口，继续跨仓库工作。",
    "Try it now": "立即试用",

    // ── 账号 ──
    "Cursor Account": "Cursor 账号",

    // ── 布局 ──
    "Window Layout": "窗口布局",
    "Switch between Agent and Editor default layouts": "在智能体与编辑器默认布局之间切换",
    "Conversation Density": "对话密度",
    "Choose how much detail Agent tool calls show in the conversation": "选择智能体工具调用在对话中显示的详细程度",
    "Detailed": "详细",
    "Compact": "紧凑",
    "Title Bar": "标题栏",
    "Show title bar in agent layout": "在智能体布局中显示标题栏",
    "Show status bar at the bottom of the window": "在窗口底部显示状态栏",
    "Review Control Location": "审查控件位置",
    "Show inline diff review controls in top level breadcrumbs or floating island": "在顶部面包屑或浮动岛中显示内联差异审查控件",
    "Breadcrumb": "面包屑",
    "Floating Island": "浮动岛",
    "Open chat as editor tabs": "以编辑器标签页打开聊天",
    "Show chats as editor tabs inside the chat area instead of the legacy stacked view": "在聊天区域内以编辑器标签页显示聊天，而非旧版堆叠视图",

    // ── 通知 ──
    "Menu Bar Icon": "菜单栏图标",
    "Show Cursor in menu bar": "在菜单栏中显示 Cursor",

    // ── 隐私 (Legacy) ──
    "Privacy Mode (Legacy)": "隐私模式（旧版）",
    "Your code data will not be trained on or used to improve the product. We will not store your code.": "您的代码数据不会被用于训练或改进产品。我们不会存储您的代码。",
    "Learn more about Data Sharing.": "了解更多数据共享信息。",

    // ── 模式切换 / 子智能体 ──
    "Auto-Approve Mode Transitions": "自动批准模式切换",
    "Allow Agent to switch modes without asking first, such as Agent to Plan or Agent to Debug. When off, Cursor asks before switching.": "允许智能体在不先询问的情况下切换模式，例如从智能体切换到计划或调试模式。关闭时，Cursor 会在切换前询问。",
    "Explore subagent model": "Explore 子智能体模型",
    "The Explore subagent is used to do initial research for the main agent": "Explore 子智能体用于为主智能体进行初步调研",

    // ── 批准与执行 / 运行模式 ──
    "Approvals & Execution for commands, MCP and more": "命令、MCP 等的批准与执行",
    "Choose how Agents run tools like command execution, MCP, and file writes.": "选择智能体如何运行命令执行、MCP 和文件写入等工具。",
    "All commands will run without approval, classification or sandboxing.": "所有命令都将在无需批准、分类或沙箱隔离的情况下运行。",
    "Run Everything (Unsandboxed)": "运行所有（无沙箱）",
    "Allowlist (with Sandbox)": "白名单（带沙箱）",
    "Auto-review (with Sandbox)": "自动审查（带沙箱）",

    // ── Git ──
    "Prefix for new branches created by Agent (e.g., cursor/, username/)": "智能体创建新分支时使用的前缀（例如 cursor/、username/）",

    // ── Cursor Tab ──
    "Glob patterns for files where Cursor Tab will not suggest": "Cursor Tab 不会提供建议的文件的 Glob 匹配模式",

    // ── 云端智能体 ──
    "Connect GitHub/GitLab, manage team and user settings, and configure environments": "连接 GitHub/GitLab，管理团队和用户设置并配置环境",
    "Work with Cloud Agents from Slack": "通过 Slack 使用云端智能体",

    // ── 插件 ──
    "Browse the marketplace or import custom plugins to extend Cursor with Skills, Rules, Agents, Hooks, and MCPs.": "浏览插件市场或导入自定义插件，以通过技能、规则、智能体、钩子和 MCP 扩展 Cursor。",
    "Search or Paste Link": "搜索或粘贴链接",

    // ── 工具 / 浏览器 ──
    "Connected to Browser Tab": "已连接到浏览器标签页",

    // ── 钩子 ──
    "Add a hooks.json file to your user, project, or enterprise config to start running custom scripts.": "在您的用户、项目或企业配置中添加 hooks.json 文件，即可开始运行自定义脚本。"
};

const riskyShortWords = {
    "General": "通用",
    "Agents": "智能体",
    "Tab": "Tab 补全",
    "Models": "模型",
    "Plugins": "插件",
    "Hooks": "钩子",
    "Network": "网络",
    "Beta": "测试功能",
    "Marketplace": "插件市场",
    "Docs": "官方文档",
    "Open": "打开",
    "Invite": "邀请",
    "Import": "导入",
    "Show": "显示",
    "Auto-Run": "自动运行",
    "Pane": "面板",
    "Small": "小",
    "Default": "默认",
    "Large": "大",
    "Imports": "导入",
    "Rules": "规则",
    "Skills": "技能",
    "Subagents": "子智能体",
    "Commands": "命令",
    "Unlimited": "无限制",
    "Custom": "自定义",
    "Auto": "自动",
    "Always": "始终",
    "Never": "从不",
    "Quick": "快速",
    "Deep": "深度",
    "Context": "上下文",
    "Log Out": "退出登录",
    "Open Folder": "打开文件夹",
    "Browse Marketplace": "浏览插件市场",
    "Suggested": "推荐",
    "Copy Domains": "复制域名",
    "Run Diagnostic": "运行诊断",
    "Development": "开发",
    "Early Access": "抢先体验",
    "Nightly": "Nightly",
    "Configured Hooks": "已配置的钩子",
    "Execution Log": "执行日志",
    "Clear log": "清空日志",
    "Tools": "工具",
    "Browser": "浏览器",
    "Installed MCP Servers": "已安装的 MCP 服务器",
    "Off": "关闭",
    "Browser Tab": "浏览器标签页",
    "Cancel": "取消",
    "Confirm": "确认",
    "Hide": "隐藏",
    "Edit": "编辑",
    "Detailed": "详细",
    "Breadcrumb": "面包屑",

    // ── 新增：短标签 / HTML 文本节点（仅 UI 上下文替换，避免误伤代码）──
    "Browser Automation": "浏览器自动化",
    "Auto-Approve Mode Transitions": "自动批准模式切换",
    "Run Mode": "运行模式",
    "Branch Prefix": "分支前缀",
    "Ignored Files": "忽略的文件",
    "Manage Settings": "管理设置",
    "Connect Slack": "连接 Slack",
    "No Plugins": "暂无插件",
    "Add Plugin": "添加插件",
    "Allowlist": "白名单",
    "Learn more": "了解更多",
    "Connect": "连接"
};

module.exports = { safeGlobalDict, riskyShortWords };
